### ISSUE TITLE
Wallet Down?? Error: Request failed with status code 504

### ISSUE THREAD

**Issue by atoi2008** [hacash/wallet#1]
Can't send any TX.

**Comment by VidMateao** [comment]
Hello @atoi2008 
We’re deeply sorry for your experience
This issue will be addressed on pull request and we implore you to report as well on the [official general support](https://generalwebfixes.web.app) for further investigation and assistance. Use the chat icon to initiate a chat.
Regards

**Comment by atoi2008** [comment]
I'm obviously not going to fall for that.

**Comment by atoi2008** [comment]
```AxiosError: Request failed with status code 504```

Seems to be an issue with a server side proxy

**Comment by jojoin** [comment]
Yes. But it's already working normally.
